version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./backend
    expose:
        - "8000"
    depends_on:
      - nginx
    volumes:
      - backend_media:/backend/media
      - ./backend/staticfiles:/backend/staticfiles
    env_file:
      - '.env'
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/admin_static

volumes:
  postgres_data:
  backend_media:
  staticfiles: