version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - react
    volumes:
      - ./backend/media:/backend/media
      - ./backend/staticfiles:/backend/staticfiles
    env_file:
      - '.env'
  react:
    build: ./frontend
    restart: always
    container_name: react
    ports:
      - 8080:80
    env_file:
      - './frontend/.env'
    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/admin_static
      - ./frontend/node_modules:/frontend/node_modules

volumes:
  postgres_data:
  media:
  staticfiles:
  node_modules:
