# Generated by Django 5.0.2 on 2024-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Подтверждение'), (1, 'Выполнен')], default=0),
        ),
    ]
