# Generated by Django 5.0.2 on 2024-03-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_is_individual_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.order'),
        ),
    ]
