# Generated by Django 5.0.2 on 2024-03-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_detail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='core.material'),
        ),
    ]
