# Generated by Django 5.0.2 on 2024-03-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_range_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price_by_square_meter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
