# Generated by Django 5.0.2 on 2024-03-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_detail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
