# Generated by Django 5.0.2 on 2024-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='svg_file',
            field=models.TextField(),
        ),
    ]
