# Generated by Django 5.0.2 on 2024-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_detail_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXFSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
