# Generated by Django 5.0.2 on 2024-03-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_detail_count_alter_detail_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_individual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
