# Generated by Django 5.0.2 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='incut',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
