# Generated by Django 5.0.2 on 2024-06-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='range',
            name='thick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='core.thickness'),
        ),
    ]
