# Generated by Django 5.0.2 on 2024-06-23 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_material_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cut_type', models.CharField(max_length=70)),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
    ]
