# Generated by Django 5.0.2 on 2024-06-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_materialgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price_by_incut',
        ),
        migrations.RemoveField(
            model_name='material',
            name='price_by_square_meter',
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='price_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='price_v',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='material',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
