# Generated by Django 5.0.2 on 2024-06-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_thickness_range_thick'),
        ('core', '0020_remove_material_price_by_incut_and_more'),
    ]

    operations = [
    ]
