# Generated by Django 5.0.2 on 2024-06-23 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20240624_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='range',
            name='thick',
        ),
        migrations.RenameField(
            model_name='range',
            old_name='stop',
            new_name='finish',
        ),
        migrations.AlterField(
            model_name='material',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='cut_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.material'),
        ),
        migrations.AlterField(
            model_name='materialgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Thickness',
        ),
    ]
