# Generated by Django 5.0.2 on 2024-06-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_materialgroup_materials_material_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='range',
            old_name='stop',
            new_name='finish',
        ),
    ]
