# Generated by Django 5.0.2 on 2024-06-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_range_thick_rename_stop_range_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialgroup',
            name='materials',
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='materials',
            field=models.ManyToManyField(related_name='groups', to='core.material'),
        ),
    ]
