# Generated by Django 5.0.2 on 2024-06-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_thickness_range_thick'),
        ('core', '0022_rename_stop_range_finish'),
    ]

    operations = [
    ]
